version: '3'
services:
  base:
    image: "mysql"
    container_name: "MYSQL_Base"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - base_mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  backend:
    image: "app_golang"
    container_name: 'Backend_Go'
    environment:
      DB_USER: root
      DB_PASSWORD: secret
      DB_HOST: MYSQL_Base
      DB_PORT: 3306
      DB_NAME: tarea3
    ports:
      - "8000:8000"
  frontend:
    image: "app_react"
    container_name: 'Frontend_React'
    ports:
      - "3000:3000"
volumes:
  base_mysql:
