apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-redis
  namespace: proyecto2-1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50


# kubectl apply -f ./hpa/hpa-redis.yml -n proyecto2