KERNELDIR ?= /lib/modules/$(shell uname -r)/build

obj-m := ram_modle.o

all:
	$(MAKE) -C $(KERNELDIR) M=$(PWD) modules
	go build -o backend main.go

clean:
	$(MAKE) -C $(KERNELDIR) M=$(PWD) clean
	rm -f backend