# Service server go
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - port: 3256
      targetPort: 3256
  type: LoadBalancer
---
# Deployment server go
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec: 
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server-container
          image: iskandar1412/server-go:v1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
          ports:
            - containerPort: 3256

# sudo docker build -t iskandar1412/server-go:v1 .
# sudo docker tag iskandar1412/server-go:v1 iskandar1412/server-go:v1
# sudo docker push iskandar1412/server-go:v1

# kubectl apply -f ./deployments/deployment-server.yml -n proyecto2
# kubectl delete -f ./deployments/deployment-server.yml -n proyecto2