apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-services
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST
spec:
  rules:
  - host: 34.31.114.164.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ingress-traffic
            port:
              number: 80
---
apiVersion: split.smi-spec.io/v1alpha
kind: TrafficSplit
metadata:
  name: split-service
spec:
  service: ingress-traffic # Se recibira el tráfico
  backends:
  - service: api-redis-service
    weight: 50
  - service: client-service
    weight: 50

# kubectl apply -f ./ingress/. -n proyecto2
# kubectl delete -f ./ingress/. -n proyecto2