# 35.202.6.186   ingress controller
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-api-redis
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST"
spec:
  ingressClassName: nginx
  rules:
  - host: 35.202.6.186.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-redis-service
            port:
              number: 7980
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-client
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"
spec:
  ingressClassName: nginx
  rules:
  - host: 35.202.6.186.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client-service
            port:
              number: 3255

# kubectl apply -f ./ingress/. -n proyecto2
# kubectl delete -f ./ingress/. -n proyecto2