apiVersion: split.smi-spec.io/v1alpha
kind: TrafficSplit
metadata:
  name: split-service
spec:
  service: ingress-traffic # Se recibira el tráfico
  backends:
  - service: api-redis-service
    weight: 50
  - service: client-service
    weight: 50